### ISSUE TITLE
Uncaught Error: ENOENT: no such file or directory, stat '/Users/ck/Library/Caches/Cleanup At Star...

### ISSUE THREAD

**Issue by ck-jrd** [eprincev-egor/atom-Selectors#2]
[Enter steps to reproduce below:]
1. Toggle Selectors
2. ...
3. Error, and Selectors isn't toggled.

**Atom Version**: 1.6.0
**System**: Mac OS X 10.11.3
**Thrown From**: [selectors](https://github.com/eprincev-egor/atom-Selectors) package, v0.1.7
### Stack Trace

Uncaught Error: ENOENT: no such file or directory, stat '/Users/ck/Library/Caches/Cleanup At Startup/Transmit/E2EFB3A6-653C-4AED-B935-04CF04F202C6\index.php'

```
At fs.js:854

Error: ENOENT: no such file or directory, stat '/Users/ck/Library/Caches/Cleanup At Startup/Transmit/E2EFB3A6-653C-4AED-B935-04CF04F202C6\index.php'
    at Error (native)
    at fs.statSync (fs.js:854:18)
    at Object.fs.statSync (ATOM_SHELL_ASAR.js:225:16)
    at [object Object].module.exports.Walker._walk (/Users/ck/.atom/packages/selectors/lib/Walker.js:62:23)
    at [object Object].module.exports.Walker.walk (/Users/ck/.atom/packages/selectors/lib/Walker.js:22:14)
    at [object Object].module.exports.Finder.createMap (/Users/ck/.atom/packages/selectors/lib/Finder.js:39:10)
    at Object.Selectors.toggle (/Users/ck/.atom/packages/selectors/lib/selectors.js:80:25)
    at Object.<anonymous> (/Users/ck/.atom/packages/selectors/lib/selectors.js:20:29)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:570:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:378:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:97:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:04.2.0 link:open (atom-text-editor.editor.is-focused)
     -0:02.3.0 selectors:toggle (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "wrap-guide",
      "close-tags",
      "acf-snippets",
      "wordpress-api",
      "autosave",
      "fuzzy-finder",
      "language-c",
      "language-clojure",
      "language-csharp",
      "language-gfm",
      "language-git",
      "language-go",
      "language-java",
      "language-make",
      "language-mustache",
      "language-objective-c",
      "language-perl",
      "language-python",
      "language-shellscript",
      "language-todo",
      "language-toml",
      "language-yaml",
      "markdown-preview",
      "metrics",
      "open-on-github",
      "archive-view",
      "linter-scss-lint",
      "rainbow-selection",
      "language-textile",
      "swackets",
      "atom-pair",
      "tool-bar",
      "tool-bar-main"
    ],
    "packagesWithKeymapsDisabled": [
      "php-cs-fixer"
    ],
    "themes": [
      "atom-material-ui",
      "one-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
atom-html-preview, v0.1.18
atom-material-ui, v1.2.8
atom-minify, v0.7.1
autoclose-html, v0.23.0
autocomplete-sass, v0.1.0
color-picker, v2.1.1
emmet, v2.4.2
file-icons, v1.6.18
highlight-selected, v0.11.2
imdone-atom, v1.3.29
less-than-slash, v0.12.3
line-diff-details, v1.2.0
linter, v1.11.3
linter-jshint, v2.0.3
linter-php, v1.2.0
minimap, v4.21.0
minimap-git-diff, v4.2.0
php-cs-fixer, v2.5.6
pigments, v0.24.5
rainbow-extensions, v1.0.4
rainbox-tabs, v2.0.0
selectors, v0.1.7
sync-settings, v0.7.2
wordpress-dictionary, v4.4.0

# Dev
No dev packages
```

**Comment by eprincev-egor** [comment]
so... i added 'try catch'. Please update plugin and try again. If after the update(v0.1.8) all is well then please comment here.
